In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

3.36 ms ± 174 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
146 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 4.1 NumPy ndarray

In [4]:
data = np.array([[1.3, -0.3, 3], [0, -2, 1.2]])
data

array([[ 1.3, -0.3,  3. ],
       [ 0. , -2. ,  1.2]])

In [5]:
data * 10

array([[ 13.,  -3.,  30.],
       [  0., -20.,  12.]])

In [6]:
data + data

array([[ 2.6, -0.6,  6. ],
       [ 0. , -4. ,  2.4]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')