In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

3.36 ms ± 174 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
146 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 4.1 NumPy ndarray

In [4]:
data = np.array([[1.3, -0.3, 3], [0, -2, 1.2]])
data

array([[ 1.3, -0.3,  3. ],
       [ 0. , -2. ,  1.2]])

In [5]:
data * 10

array([[ 13.,  -3.,  30.],
       [  0., -20.,  12.]])

In [6]:
data + data

array([[ 2.6, -0.6,  6. ],
       [ 0. , -4. ,  2.4]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [9]:
# Creating ndarrays
arr1 = np.array([1, 2.5, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1, arr2, sep="\n")

[1.  2.5 3.  4.  5. ]
[[1 2 3]
 [4 5 6]]


In [10]:
print(arr2.ndim, arr2.shape, sep="\n")

2
(2, 3)


In [11]:
print(arr1.dtype, arr2.dtype, sep="\n")

float64
int32


In [24]:
print(np.zeros(3))
print(np.ones((2, 3)))
print(np.empty((2, 3, 2)))

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1.48010764e-311 1.48010764e-311]
  [1.48010764e-311 1.26974871e-321]
  [1.89146896e-307 3.76231868e+174]]

 [[5.44911626e-090 1.95103613e+160]
  [1.26037723e-076 1.52111014e-051]
  [3.99910963e+252 1.90979636e-312]]]


In [25]:
print(np.full(shape=(2,4), fill_value=False))

[[False False False False]
 [False False False False]]


In [26]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Casting, astype always creates a new array
arr = np.arange(10)
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype, sep="\n")

int32
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [31]:
float_arr = np.array([1.3, 1.5, 2.7, 5.9, 2.3])
arr = float_arr.astype(np.int64)
arr

array([1, 1, 2, 5, 2], dtype=int64)

In [32]:
str_arr = np.array(["1.3", "1.5", "2.7", "5.9", "2.3"])
float_arr = str_arr.astype(np.float64)
float_arr

array([1.3, 1.5, 2.7, 5.9, 2.3])

In [36]:
# Arithmetic with NumPy arrays
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print(f"arr: \n{arr}\n")
print(f"arr + arr: \n{arr + arr}\n")
print(f"arr - arr: \n{arr - arr}\n")
print(f"arr * arr: \n{arr * arr}\n")
print(f"arr / arr: \n{arr / arr}\n")

arr: 
[[1. 2. 3.]
 [4. 5. 6.]]

arr + arr: 
[[ 2.  4.  6.]
 [ 8. 10. 12.]]

arr - arr: 
[[0. 0. 0.]
 [0. 0. 0.]]

arr * arr: 
[[ 1.  4.  9.]
 [16. 25. 36.]]

arr / arr: 
[[1. 1. 1.]
 [1. 1. 1.]]



In [38]:
# Comparison
arr2 = np.array([[0, 3, 3], [3, 7, 1]])
print(arr2)
print(arr2 > arr)

[[0 3 3]
 [3 7 1]]
[[False  True False]
 [False  True False]]


#### Basic indexing and slicing

In [43]:
arr = np.arange(10)
print(arr[5])
print(arr[5:])

5
[5 6 7 8 9]


In [45]:
arr_slice = arr[0:3]
arr_slice[0] = 1000
arr

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [46]:
arr_slice[:] = 99
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [47]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7 ,8, 9]])
arr2d[2]

array([7, 8, 9])

In [49]:
print(arr2d[2][0])
print(arr2d[2, 0])

7
7
